# Generated by Django 4.2.1 on 2023-06-21 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_bio_profile_city_profile_social_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='current_city',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='fullname',
            new_name='full_name',
        ),
    ]
