# Generated by Django 4.2.1 on 2023-06-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_city_profile_current_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Website_or_Portfolio_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tech_stack',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
