# Generated by Django 4.2.1 on 2023-06-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_website_or_portfolio_link_profile_tech_stack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
