# Generated by Django 4.2.1 on 2023-06-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_profile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Profile_picture',
            field=models.ImageField(blank=True, default='/profile_pics/default.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
