# Generated by Django 3.2.15 on 2024-05-17 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_profile_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='social_link',
        ),
    ]
